import org.junit.jupiter.api.Test
import kotlin.test.assertEquals

internal class Dec03Test {

    val exampleRucksacks = """
            vJrwpWtwJgWrhcsFMMfFFhFp
            jqHRNqRjqzjGDLGLrsFMfFZSrLrFZsSL
            PmmdzqPrVvPwwTWBwg
            wMqvLMZHhHMvwLHjbvcjnnSBnvTQFn
            ttgJtRGJQctTZtZT
            CrZsJsPPZsGzwwsLwLmpwMDw"""
        .trimIndent()

    @Test
    fun verifyExample1() {
        assertEquals(157, Dec03().sumOfPriorities(exampleRucksacks))
    }

    @Test
    fun verifyExample2() {
        assertEquals(70, Dec03().sumOfBadgePriorities(exampleRucksacks))
    }


    @Test
    fun puzzlePart1() {
        assertEquals(8153, Dec03().sumOfPriorities(puzzle1Rucksacks))
    }

    @Test
    fun puzzlePart2() {
        assertEquals(2342, Dec03().sumOfBadgePriorities(puzzle1Rucksacks))
    }

    val puzzle1Rucksacks = """
        VdzVHmNpdVmBBCpmQLTNfTtMhMJnhFhTTf
        FgqsZbqDDFqRrhhJnsnLMTfhJG
        bRRRPrRRwSwbDqgjvDZbRbQzpzmQVWCzzBdvQBFCzlWV
        GcDdRdvhRssRhGDdShCRtqWjlQzqWgqzNfNjfQWWjt
        mwwnnPFwmVrPmJmzfNzqCjQCbgVlgC
        nPnHHLrHwmJTrCTJpThBscBSdSLGZvZBvRhZ
        RVQQcVlcSRclfZCCCnMJJTSTnC
        NdHwjdwjbBBZrrZrbJDZJJ
        wmhjGGBGwwmjtjtdPlfRcpVQlhRppVJF
        pplbNBPPrppllrFNbpvppSTcwqcWFhTTShhJDTchqd
        RGzRfLjjmZmfmwLftTWhStStJWTdWmDm
        nfsMjQssnpPvNnrPrw
        SjjBgllzlQjBZvlBBgcFbgJHsMhJqbMHPggJbM
        hRLRVDdRRWnJqnnHTqMCnH
        GRfLddRRpVhNVrWSjwQQzSzcGSBQSc
        qMwNqqBdQdnTVBBVVhMVnVFzTHPggTPjGRDzvPTjjmvPDj
        sbSrWJpStrtPtRPttzmmDD
        pfbJJcbsrcLpWLllsnFmcqcwQncnQQqVNQ
        RBTWCMwCwdZThPZcZZ
        pVmVpHLFFFHHVgVmvNmHSQNvddlPPzZJMPcdhclhjczLdZMP
        vnnNnFStGMRDwWnn
        fWDdJTpDJzdBBBdmDSbSRHRwPqbPbHgSbz
        slQtQvNsMVvrrgPRgRglnhwWPH
        sGMMQFrsjvNMfWmdpfFDFZBf
        vnMRMWCMJwWWwwWPjmSdVmLdzvVbLrhL
        HsNfDHQlZpNqfQzbLbrqhjLmVdjd
        dfDZQsNpstHHHptZDDtZWgngtgBMPMMRwCPtBBGW
        HwQwwbwFNWHwHBVFQFLQzRznZnSzcjjjpPbcPpSP
        vTfTJsCmsftJZmTSSdPvzdjRSvPdjd
        TrGtTJfmGDfDhrhJJJsqrZhDBFLHHLLQWFwwlWBVBBVwgLFD
        FFTJRLccQgmTbSsbGm
        PBPPqCvCwqwhQQVhQngmVmSgglmGnHbnmb
        zqthvtQPBfCCzPwQPtwQzPwNLfNRFNLdLRLFRFFNLFdFdW
        nszjQnsPwjznzCCrhJqvjqhmBv
        tFWdHGWFGtctlNNpZBBhmqTrrbWqvTBT
        dlFtcpHDVVVHFdNGHGpGfQgsPDzSMsQwwPwgLLBQ
        TzQqTJGvnnSzqrWTnvfbbcflQcVltfcCMPVM
        jFjNZFFJLpFwmBwblcpptcVtfbbVlR
        jmmJdBBLNdGDWDDrdzqn
        pzddqQmGgbqgGpbJmmdnLZDCRZnZvFlLRZLSlLRT
        rVwchcBBMwVBHhHTZCTSGSCRTZlTDr
        HtccPfjfBhMtVBGHWpNqJdJdpjNJppWz
        WThTWWhtPbZRvvWbbvRTSRMjVRLLgFssgLpVsfSF
        JdwrlJcCwfzdqwwjsjzpLMgVsMFgML
        lQrwHNGJHClvTmfhBmPQmt
        lbRLhcLRpLJzgdGddF
        qvhwqDDCVtBDVhfMVGFnzGGzTBnGzGGgFg
        VjCwCWCMtjVDtChvQhtffcSmHpNWrrcHZHHZpplWbp
        DJVDVdvpmZdPgrCbgbgCJC
        lzczcWwwznGhBgPSvTlCrNgqNC
        wGzzQhzGGsBBGRBcQwGwnwjmmRHpRfmmMpppMjjHDvLL
        HJjJQWjFmmWtFmJTMchghhDwNMhVMWML
        SznPSRfRSSPdrrPSShbDVhbLPwcwGGwVNh
        ddRfzdRrCrRsZDSnFjspvFvqFqFqTvJt
        lflfjQfjvljfbfMLTTDCmHNLNVbL
        HSJnRrrJZJssnGRrnsrcqqRnDCLBMhVCTLVLhVNVJBBBhhBm
        SsrGGqqnSsWSnnqWHSrPfzftvFdvWlwfQgQwWvzz
        nQlsGnFGwwqNJWmJJjpplt
        HMTLPTRdvsTCCThDCZdLdLDNNpJBWJbjJMpBmbtNptBWmm
        DLCzPzTzZDdLdGSGfSGrsnQGzr
        LNPPLHNPHQNQSBFDWDPgggFv
        hszfWCWJhrBMsSSBgvFD
        GGZjfmJTjmZfrJrZrZJRGwNQnlLNHWjLVjlwdVNHpV
        BdNVdTcGVclmTwrTnwPwrHCr
        zttBWzfLsCggHPwDrf
        szsWSMbWzzbqBbzJjtjsvMzzvdmdVpGllpcRNZZhmRpZcGGc
        CjdbMmmmZFnzzgHlttGBVqtBGtsldG
        LvPPWNcFSSRslWhBsllT
        ppccvLPpcSNwLLwrDNNpLvwJHCMDmbCJbFzgmZZmFgbgnM
        TTNRwZqhcTTjsNTTsmrJlvrmmmqqHSrlJH
        fLQCCdtcfCDDVbVVQdFbQbdJHMHrJHrHnMllHdMHPrMdln
        WfQLQWWDbwRTWcRssN
        HQGQWHPDHNjMNQGNWNTWCvZllzqFZqzvvzhCtvFj
        DfgwdgfcFpchztvt
        sRggdwwVdgmnSTnnDBPBNWLn
        WbCZCfTVTTJjSwGdWNDGGw
        MMRqggMsqhlmlhrssHgRnRmRvdzdczvdNGNLzScGDrNzrLNc
        lRqsnRhmqqQnQpgQMlgDqRfBTJVFbJZQtBCbZQJVZFFb
        JnhQcCnmLDsmgmgr
        bbMZppRFGGRPfBMMRGMZssTTrLlLfsLlVLdsLsdn
        GZGSpPGMZtGGPFFRGBCwhvwjjcnJctvQcvHq
        vvrPrHZMGJNRMnqn
        BVChWWcDVWsBwCWwGrJNhRLJJnJtLqnq
        cjDfcfpWWsfWccBsHgPgrPTdpZbbgggv
        GshtVtVtjSCVtVvVGtlVvFZLMvLRZmHmZwbLwZdLdZmR
        JWzNDQzjcgJgQBJgzgMwLLHZZcdPwRLwRdHZ
        QWTppBWfDrrNBTTfffhFCpVSjnhCGsFtsqSl
        nmbCnzHHNzCjCJHJNSCWHLBLrvBrrSGRBDhrDRLrGL
        TVtPllwcgdmTRhLQTQhT
        fdFtccFcpPmggfdfNzHzCMsbCnWnJs
        fMgddvjgRRvjvjVJVdTlZGGtGnrlnqTccNjl
        HHSFSWSmmpbBpZlGncrNGbNtrn
        WDWBDDBDBDCwPBWBDWNQDgzvVvLRvsVLRwvwdJVLwL
        ZSmmvcpsmcJmJvqgBZgZqqtCtZjl
        WhDwhFSDgtBFjnFg
        rTrSTLWTTHNMNwNrMVddwNNhsmJGQcRsRcJGsJzQJsrzPsPm
        GBtLmPsCQqsGqgghZHDzzgLbFz
        zjjVTzTlRjRJfznrvrfpnNhFSghbbNFgHrbHZbDHbH
        vpfcTJVpcVlfcQPMPCGzCBsd
        HMhZNffcPZfNMrzjjFdGcJDjvJ
        VSBVVLlSQQmTVSWpSQzDrHzTTvDvFjFdGGzT
        mQSplVHWbHLSgWQnShNwsZMZPfbsNCRNCt
        MMqvDzLwZzlMqQfdGWPfgPffPglH
        ShTcJshsrRdnrdfrrfHp
        VVRtFhsCJVJVvwQqDdbDQd
        dmnNMlFNvmvljnbpMWNDFQvfQJJGvfPCfHGgQQgcJg
        bRVzLBSSTRBRBBrwTrVtRwCfcGHcsJgJgzgGsggHCzcC
        ZbtVTTrrqrSSVwhqqwBRwFWMDFNdjdZpWjdDDppjMW
        MTzqtbLtwFzJgbHgfbdWWH
        VMNBjNVjvNfhhhhfNPhP
        jmGMvlDZZnVMtzlwzqqCpwFt
        PpzGspGmpPsFLrTnTLzzBg
        QCWvfjfWjRPFZgrvqrBvTg
        wwNRCNQQVNRWjNWfQbHCCClHGDGJdGhpdhtPGhltDlJD
        dhbpGzhllzGlPvnzNcvtNVnc
        gcFMsTJDMMwrZqfjjqvvfnPtqJ
        sWRWTRFwrTgLDDFWgMsTlpSlpbSCdWWdcbmpChGd
        QccdFFFcFbcQPQPHMgpPMp
        NJlNSSMLDfJfmlSqHZRNpRqNBRPRPq
        LlMmJfvDVVTJSmVMscsCFtvwcjWjrjCj
        NVVMGWFSMRVGWSthwhTJWzcJCcJsTs
        jqRLqlfRZcmjcCzT
        rlRRrdrflpdvPbHpflfPlfDBgBMQpGVQMgpVDGMggBDV
        VwRhccRsnQStRhtGQVQVsmjgDgqJdggDjqLDgJlLzmLl
        BWFZpWHBNCBCNBzBNvWBpzHZqqlMqgNdlllDdqDgJDLlfDdd
        pFbTrrrBzbzTtSwStQnnsrVn
        DRfFbFqzbddfPFtsJnJRsnClJRsn
        cgjgQgWvSLVQgmWWgWVjVSSSBTltThLnqJssnTCZsTThntZT
        qjwpSrmWgcSrGMfdFDFdwHFd
        RWjDDWDjDNjjgDtSRRgjcjzFpnzwdFbFNdbFbpnldwFF
        vQfPfTQJbZdThTzL
        PrBQJQsfQqrrbfmPqMBfJbggjRVgWjttsHRSgRctDjSs
        NgqNWqqWWdnJdqpBNFtCmJGCDHttDGDsHsHm
        BjvzhRLTrTBQhTMQRjRRcjPGtmDCZZDZSCmmMSSZmVmSSt
        vQzRvRzQcPcvfQzRnddppFgnFfWwBFlb
        nnPvfvgrtPDHgvvGTRRRPZQGpGCLLV
        FlBsBdbllFdfWpbGMCVMZLVbZQ
        lhchNcqFsJBlBszztvwHjvzgrzmzffgH
        zZhdjTpJJpjmmpPZhvqnnZHqZcggvgMbgv
        tFpFQFSFtBGlFNwFfNMnHfbHcnvcvcfvcqrM
        GBFlNLSNVGVSSGtQSLLBBlNtphDdzpmmPmTPhRmdzdVCCDdR
        rpRCCDLpmnCdJCjn
        vMhSFvgsMGLmnmWMmm
        wVqFFvwvPPHhFhhgHPwHshpqrDDzqlfRbpftRLblrllr
        CRNDzdJCVDWzVgDjdjzRJzWRMTbHsMNZNbZMMbsfhTtMTLMB
        wSlwQcSpqPpcqcqFSqpwslsTfZtLhtlthtBHtTMZ
        SPGFGFFmpcPGDrWDmjDJVffR
        dsmdtJthJphWqHRPnRRsvvnnfR
        cDBMDDDlBZglDZTMDfzVvNRrvNPVHzRRTV
        PGMCCDClBDDbbFqmmhqQdpWGmmWp
        BJjcGhcvCnBdGHsmHSzZDzSDMHmRMQ
        qLWPLVrTwWlwwwrfrFfGDNmDQRMbQMzzmmbQLNMM
        rVWrFlGqlqwVwVGgWGphnvgBBsnvsjdBnCBnBg
        sNNsfBsmcGmgNTcHHSpnTWHnpV
        QlrhlrlMglhDQrdFblvFtMdnDWwSHDWWwnTSjLwVDSwwwT
        QtdMvltZhbFlPPZbQtQthZQdqCsJJGzBqqCBmCNCqgRCBsfP
        SZnQnnHRWRQRVjHnqlJTQPfdlqfJftqG
        pDzmbDBFbBLvvzttfdlTTl
        gsDLLpcmsSZVwlnRsV
        LHsWjwjWqCLsqCHcLsjdLqcdbpMGZPPtBhthbZBpBhMllwPG
        VFnVbbvJSfbgphSpGlhRBBSP
        JrrTgmFgzvNbrmNnmnvzgTLjCQWDLDCsTjssjqcHLc
        QmwwqTqsrdqNNqgtvnVDVcGNNtvv
        WBFBpzzjSJBJzJbfntgPzVzcvPnzDf
        HcpbHZJBFpjpcSZrZsdRQZrCwrwd
        JqmLmbtTWThBTWvWGVSrrVDsSGSG
        wwzRzNjNNbsPVPds
        jfgQRZwpQclQfffHgpRpwpfTcqtLLqCbbFFFLmbmTTBnFB
        fGpcccNNqcctqGMprvMPmbbzFSflSRzPBBlBbS
        JCjnjTZTTGPSGmTFPb
        ZWHhJjHLDVDgHLLDGjnhctsstwqctNwWqNwwQrtv
        sDwQhcwhBDDwrhGsQnRBQHHMHHMNJMZFCFRbCRftMM
        zjjlmjqfdTqlWdzTqmLzlzVjNCHJNHNFMFtbJNZgVNMMCCtN
        vPTfLmPTLWBsPDnSscnS
        ngznwDPPTzhPPDCTQnTTDQBQqHNNrHFVppbbjRFFqFhHqRqr
        tZJtcGsGtLLcctRqVBbbqrspbHNq
        BmZSvGBMdWPzMPgnnz
        MpNWPVNWWZWVVNZHVcvJjgBjJMStMJSjjg
        rzdCzrCTTLRCslvJDSjjdScgDm
        RLhCQzqTCssThRQzRzwGQrrCFffbfWppNpWNWVcHqZbHpVPp
        zQzCVWdSSjCdjpchWcGftflGZcgG
        RwnJTJwmvFHTBFmtBccZZfBGMstllM
        wwvvHRwqDnHFrmqnrSbQVVQfSbqQjbqjbQ
        ttDftStSlftPgSHmJbFwnMnFwzbrLHMMzz
        GqTBqhBqBvppBvMMTznrCbCnLwfr
        RBjjpZZvvZqGcNhjjpNmDPfDcsgfDfgScsQQQg
        rsSFccvBHppHPsvQrSHSprFjnbLGdbzLfbGLLtLjjzLzvl
        JWWJhmwwTDTGtnzlhdbtLG
        CWNqWRNCwnCJVppQFFFFNrgHBB
        MSRVnMjnVRVnPlcsrtMtschgDl
        NWHBwJBwBBQCHHqwWQGBNgdrFFtsthcqdltdDsqttq
        CCTTGCNCCBfNJNNWbGGnvVzDSRfDRSZvLPSzRn
        MpRfjRjWpZzzzRzZSpjzZjTCQcGdHLWNGqdBdcBWWBLccn
        lrbrsPQDPQglDtwggcLCqnCdNNdHBLsqNd
        blwbJggvgbwlvQbvtgwmvVwRfTzfMMjFVfSFjZjMTSTSzj
        ttSGjHWVrwWrWWvhzvhmhDfR
        qMBdNNsccQgfDRzRmqlhRl
        gQJdfJPdQBsMggMjPrTCLjrGrCrtVT
        tGFdlwDwGFdNtStghWWdQFSnTVfCfZhrfVTVCVprnRRhVn
        cLsBPQJsQPmbmPHTnRRnHprCVfns
        MjmvPqqQjPbQzjLwwDWDSlzSlGSgwl
        NSCpFgfbscbZZZwrtgPZJT
        zGCQlVGmmQGVqqJwGtHZGrPHHRTH
        qQvVmvzmqCdhhjzCQLjljLQMnMDSFWcSfnMfpbfnNcFFbFDN
        zFgqjQBmWNlWlfHrHdLc
        wnbCpSSZZTJSJSnmdrtHfGtftlcpltpH
        ZSwhVPPJgNVmNFzs
        WNVJthVHRRfLqpqN
        gdCGcCgJBCrgScRLzbjQQLfRRR
        SCFdGSFvlhTJsnvW
        FFZwFZZwRmFFhHtNLNLGRtsqjLMt
        gbDnnrMbMCffMPbPLNjGNlcppNtspp
        rgbzrzDrgVgnrBzFWMWmWBwHWHShSB
        zjRVjDqzRjvSBnBGGsfsrFsV
        fLccLLZpJMctwJWWWJWpJGCwFwsgnngFBPsCnnTBPT
        LbJlZNWMtpMlHRNHzdfSDfdj
        VGbbnJGSTsVTssTTnVVWMtfBBmvftRHfHBMJJfZp
        ghqtrzgPrjdzQCjmZMHfRHZHBmQmmB
        gltFtDqFVlTVWlTl
        HqNqZDTvNvVTLPSTvzfrfHfdndffwnbdnwrH
        MpSJlFcMJmcpFlmClcMcRnWbWtthrnfwnCGrrWfrwC
        RjcJJmSFMRQpMRFjMNVvTZjNPPvLTBPBBB
        MzClDtlzJzFzNGGm
        bjcLRHlTBsFJGmRm
        HcPSSfTSpLZLbSwtrtvMnlDCDPCl
        gWWgQJCsVhgRLCWsdjpmcBHvfvrrnvCvBB
        TqDtztqtStlbNTPtllqZpvmcFHjNjvjNvHvmrrmj
        ztPPGZqTPSbJgchGgwRQgQ
        wVrdtTqtCCvbNgbNTTDN
        mhGzWhGzMGWGrRmbFLBHZRNHNvZvgB
        hhGhShpnsSrqVCVSSj
        HnlbmGnlHZHnlBcjgwfDVfwLsGLGLDgR
        WhWMWTvQPWPLDMFRCDMsVD
        QdzJQPSPZqJnJRnZ
        TTjTjFBcRBGjwsDTBLmrCftfRVrrCftCVNRP
        WnqbJWnnQJhSqVfVPfDnggfrVN
        hSlDMllvhbQqllZlSWQdSQTBjsFHBjTwGdHBTBszLzcc
        rNWqWDLZWcqFqLLLgQQJnndnQdNzzJVMzd
        cPtsPvChtRsGswHPGbwcPcdVnpzvnmBmVvJBJdJVJdzn
        PfRfRGtsHsSRftbbbbHhwCCsjZgSTgSZWDTcgDZjLqgqFWLq
        BNzPnPJNNMwHJRhBGRWRdjFQddFlFjWd
        npbZrgnLSCSrWFjjdlZGlcDF
        gqtmmngSbmgHJqfqzNBHBJ
        stgzttBPRRRdpSVVpdpS
        WJFcLQmJZHcCFLJmcZLMfbpGSWMNpGftSSpMrb
        mcvvQvHmtLCJmHZQHZHCDHJJnjqPjjPzwvwhnwPqTjPBzPnB
        DDmbbPqgFSbSQPtPQJttrltJ
        CRfcnZWmRRhJNVtsVnQlsp
        fcBvWvWzcZWCzTTCTTvccFMBHGDdSwGFFbqwFSGSmF
        tCRBPCPRjzsJszBmtjmCvSpHcppJpvZdHHHcHZJG
        qbrlLnWlQDQDNvmHHHHcrZZvdm
        nmnWnnWmgQsCFzFCRVCg
        sHMHCDZfcwMcRcLMcZDCRCHMPdJqgjvVdvqgdgfdJbQgvWQb
        FFhTzmzGrnmtjTBjBBprrmFtqGgQqvVdPbbgqQQWJvvWJQqV
        TrNjrnFSlwNZNlNL
        JQGdsdzSzsdFQFSdssnndNlZjNPTJZNljVjTPhVPhT
        GgGLfRmHGLhNVjjNTLhV
        HvGvwpbHHRwpBrvBgSSzSFndtzndCrsFMd
        DptFshMrhDhDwmPPhwSNhmmS
        RLdcdRvBjnvRVcvlcLbCcbCwwpGBwSmfZqqPPPPwzmfqZq
        VlRLvVjCJLnlpvvRdllLcJJWDHgMMHDDHtWFFDDQgH
        SsSdrndpDlCdLftd
        VGPVJgmQrVGHHZfwLlfCTmfwlDlT
        PcJHcGgcWWbJpjRrphRbFpRn
        PdPSMHMLzPPSShBdffMMzMRHQQrpppcqTCQQpCccTGTRCnCQ
        vsbWmFbmJmZFFsmsbfpGVrGnWrrpVpnnVcTV
        JZslstfZNNSSPdlSMwlM
        bLLzRzZLbRqJJrDGGVZdwssDvGQw
        FCtNJlTFtmPfldSvDvQFVVsjSv
        PmCPHBhhPpWLWgzgHJ
        qwmwFHCgPgPPqPwMCrHHFBVVRBttVRRffVfmsjVNNB
        WSvcSnvbSWbhcbjlQbvlSQhlfBGcspVVsVGfVscpzpNcpBtN
        hJSLhlvlTjPFHMLCCq
        bggDpTggncGVVWbQcG
        sRvSwwwFBSpFzvRvMFZqmPmMVqmcmPPVqhqqWq
        SRBBrFZZwrddBFRjlptnLgDnTggdtd
        PPfMcZMflbMQcMllPVfTVMwjWWmZvpWWpWhhjjpdWWww
        sDQNnzsnQgDNsFzFqtGjGmWWSpWrGhdpvphdSW
        nNQNqLBHLqzDnHgnVJfPJPCRBbfCcJlT
        fppppWsjcSDPjjDpGhgwbfTgHTCbHJwbHbTR
        rLBdQnvMNMmFPbLqHqTqgLHCgL
        nrFznvMNMQdttrBcScsDstWcPGtWSc
        lclnRSDnGZtvSwnZDZzhLffqdsCNwTBCBBdNsd
        mPjmjmrFFpmQjMJQjlNdlhCsCLsTlNLs
        ggmrHHVVQVPJpWrgpWScRvzZzGGRnZvlgzZn
        GjGJGQJGcMTVfFDQzNVQzP
        mHqdbmmdnJqVzVhRVNzPbR
        wStmHJsJsLZLjTvM
        QssMbVGdMQjZPjwVwHVZPZClllvgSgvlTgwwSSCgSCtC
        WmmFBmJrcFRBFrJJBFchzWCStgCTgvhvTlfsNqfTlvTv
        sFzzssDLzrBPjDVVddHMQD
        fztDZSGrNrlnbnPTgFFpln
        jvvQMMcLcjJmQwHdJvjQJnnbTbRFRphnnpsWgmFRPR
        vTLHHCQLHBBjJCSZrVCZtSfSfrft
        gHfHffHLjwHrRjLrLRZVMnTdTBsNTBwTVBsBnN
        DWPhqhhDhvSGvWPzSzMBQBQVMMBBmvssvQvQ
        CDGbqCDbChSbWGrHcHRgbcVcfrLJ
        frlTLmtllbbbdpJS
        qFjhzjThjHTFGHTjqhhjMzBhVpVpdbBnSJQRpBnVVdbRRQJd
        vjWPWjWPPPWgwmfCrNvTvZ
    """.trimIndent()
}